name: simple Db to Db etl 

on:
  push:
    branches:
      - main 
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:  

jobs:
  run-dagster-etl:
    runs-on: ubuntu-latest
    
    environment: Env
    env: 
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Dagster Assets
        run: |
          # Run all assets defined in your Definitions
          dagster asset materialize \
            -f src/main.py \
            --select "*"



      - name: Slack Notification Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Airflow ETL workflow completed successfully!"

      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Airflow ETL Workflow Failed."

